### ISSUE TITLE
Pre-Migration Work for SpartaSystems/holdmail

### ISSUE THREAD

**Issue by tsneed290** [SpartaSystems/holdmail-ui-vue#1]
### Issue Overview

Per SpartaSystems/holdmail#39, this project will be migrated into the SpartaSystems/holdmail project.

Some enhancements will be made to this project prior to migration, for reference purposes.

### Todo
- [x] Upgrade dependencies in holdmail-ui-vue
- [x] Remove modal experience as requested in SpartaSystems/holdmail#36 
- [x] Open links in emails to new tab SpartaSystems/holdmail#11

**Comment by tsneed290** [comment]
Work complete, migration complete, sunsetting this project.
